version: '3.8'

services:
  travelbag-app:
    image: seannnnn/travelbag-app-dev # DockerHub에서 pull 받을 이미지
    container_name: travelbag-app-dev
    ports:
      - "8080:8080"  # 호스트와 컨테이너의 포트를 매핑
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}  # RDS 연결 URL
      SPRING_DATASOURCE_USERNAME: ${DB_USER}  # RDS에 연결할 사용자명
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}  # RDS에 연결할 비밀번호
      SPRING_JPA_HIBERNATE_DDL_AUTO: update  # Hibernate 설정
    depends_on:
      - redis
    restart: always  # 컨테이너가 종료되면 항상 재시작

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
