version: '3.8'


networks:
  travelbag-network:
    driver: bridge
    name: travelbag-network

services:
  travelbag-app:
    image: seannnnn/travelbag-app-dev # DockerHub에서 pull 받을 이미지
    container_name: travelbag-app-dev
    ports:
      - "8080:8080"  # 호스트와 컨테이너의 포트를 매핑
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - travelbag-network
    restart: always  # 컨테이너가 종료되면 항상 재시작

  redis:
    image: redis:latest
    container_name: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - travelbag-network
