INSERT INTO rec_item (name, category) VALUES
                                          ('텀블러', 'OTHER'),
                                          ('여권', 'ESSENTIAL'),
                                          ('노트북', 'ELECTRONICS'),
                                          ('아이패드', 'ELECTRONICS'),
                                          ('노트북 충전기', 'ELECTRONICS'),
                                          ('휴대폰 충전기', 'ELECTRONICS'),
                                          ('아이패드 충전기', 'ELECTRONICS'),
                                          ('카메라 충전기', 'ELECTRONICS'),
                                          ('팬티', 'CLOTHING'),
                                          ('브라', 'CLOTHING'),
                                          ('폼클렌징', 'TOILETRIES'),
                                          ('클렌징 오일', 'TOILETRIES'),
                                          ('로션', 'TOILETRIES'),
                                          ('휴대용 고데기', 'ELECTRONICS'),
                                          ('보조배터리', 'ELECTRONICS'),
                                          ('잠옷', 'CLOTHING'),
                                          ('양말', 'CLOTHING'),
                                          ('스타킹', 'CLOTHING'),
                                          ('유심', 'ESSENTIAL'),
                                          ('여행자 보험', 'ESSENTIAL'),
                                          ('신용카드', 'ESSENTIAL'),
                                          ('체크카드', 'ESSENTIAL'),
                                          ('면도기', 'TOILETRIES'),
                                          ('휴대용 선풍기', 'ELECTRONICS'),
                                          ('안약', 'MEDICAL'),
                                          ('세안밴드', 'TOILETRIES'),
                                          ('모자', 'CLOTHING'),
                                          ('수영복', 'CLOTHING'),
                                          ('패딩', 'CLOTHING'),
                                          ('코트', 'CLOTHING'),
                                          ('안경닦이', 'OTHER'),
                                          ('안경집', 'OTHER'),
                                          ('우산', 'OTHER'),
                                          ('칫솔', 'TOILETRIES'),
                                          ('수분크림', 'TOILETRIES'),
                                          ('스킨', 'TOILETRIES'),
                                          ('바세린', 'TOILETRIES'),
                                          ('향수', 'OTHER'),
                                          ('가글', 'TOILETRIES'),
                                          ('가방', 'CLOTHING'),
                                          ('삼각대', 'OTHER'),
                                          ('마스크', 'MEDICAL'),
                                          ('지갑', 'ESSENTIAL'),
                                          ('도시락 와이파이', 'ESSENTIAL'),
                                          ('바디워시', 'TOILETRIES'),
                                          ('샴푸', 'TOILETRIES'),
                                          ('컨디셔너', 'TOILETRIES'),
                                          ('헤어팩', 'TOILETRIES'),
                                          ('마스크팩', 'TOILETRIES'),
                                          ('볼펜', 'OTHER'),
                                          ('현지화폐', 'ESSENTIAL'),
                                          ('종합감기약', 'MEDICAL'),
                                          ('소화제', 'MEDICAL'),
                                          ('진통제', 'MEDICAL'),
                                          ('반창고', 'MEDICAL'),
                                          ('연고', 'MEDICAL'),
                                          ('두통약/멀미약', 'MEDICAL'),
                                          ('여성 위생용품', 'TOILETRIES'),
                                          ('선글라스', 'CLOTHING'),
                                          ('신발', 'CLOTHING'),
                                          ('담요', 'CLOTHING'),
                                          ('스카프', 'CLOTHING'),
                                          ('우비', 'CLOTHING'),
                                          ('휴대용 휴지', 'OTHER'),
                                          ('물티슈', 'OTHER'),
                                          ('샤워기 필터', 'OTHER'),
                                          ('카메라', 'ELECTRONICS'),
                                          ('이어폰', 'ELECTRONICS'),
                                          ('멀티어댑터', 'ELECTRONICS'),
                                          ('헤어드라이기', 'ELECTRONICS'),
                                          ('자외선 차단제', 'TOILETRIES'),
                                          ('주요 서류', 'ESSENTIAL'),
                                          ('안대', 'OTHER'),
                                          ('귀마개', 'OTHER'),
                                          ('목베개', 'OTHER'),
                                          ('라이터', 'OTHER'),
                                          ('수건', 'CLOTHING'),
                                          ('손톱깎이', 'OTHER'),
                                          ('e-티켓(항공권)', 'ESSENTIAL'),
                                          ('신분증', 'ESSENTIAL'),
                                          ('국제면허증', 'ESSENTIAL'),
                                          ('국제학생증', 'ESSENTIAL'),
                                          ('예약한 곳 티켓', 'ESSENTIAL'),
                                          ('숙소바우처', 'ESSENTIAL'),
                                          ('영양제', 'MEDICAL'),
                                          ('벌레 퇴치제', 'OTHER'),
                                          ('핸드폰 목걸이케이스', 'OTHER'),
                                          ('긴팔', 'CLOTHING'),
                                          ('긴바지', 'CLOTHING'),
                                          ('반팔', 'CLOTHING'),
                                          ('장갑', 'CLOTHING'),
                                          ('바람막이', 'CLOTHING'),
                                          ('반바지', 'CLOTHING'),
                                          ('후드집업', 'CLOTHING'),
                                          ('젓가락, 일회용 수저', 'OTHER'),
                                          ('아이라이너', 'TOILETRIES'),
                                          ('아이브로우', 'TOILETRIES'),
                                          ('쉐딩', 'TOILETRIES'),
                                          ('하이라이터', 'TOILETRIES'),
                                          ('블러셔', 'TOILETRIES'),
                                          ('파운데이션', 'TOILETRIES'),
                                          ('비비크림', 'TOILETRIES'),
                                          ('브러쉬', 'TOILETRIES'),
                                          ('쿠션', 'TOILETRIES'),
                                          ('쉐도우', 'TOILETRIES'),
                                          ('마스카라', 'TOILETRIES'),
                                          ('뷰러', 'TOILETRIES'),
                                          ('접이식 전자포트', 'ELECTRONICS'),
                                          ('휴대폰', 'ELECTRONICS'),
                                          ('면봉', 'TOILETRIES'),
                                          ('립밤', 'TOILETRIES'),
                                          ('머리끈', 'OTHER'),
                                          ('미스트', 'TOILETRIES'),
                                          ('책', 'OTHER'),
                                          ('동전지갑', 'ESSENTIAL'),
                                          ('빗', 'TOILETRIES'),
                                          ('수첩', 'OTHER'),
                                          ('옷핀', 'CLOTHING'),
                                          ('작은 자물쇠', 'ESSENTIAL'),
                                          ('여권사본', 'ESSENTIAL'),
                                          ('수면양말', 'CLOTHING'),
                                          ('호신용품', 'OTHER');
