name: Travelbag-dev CI/CD Pipeline

# 작업
on:
  push:
    branches:
      - dev

# 작업
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v2
      # JDK 설치
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      # Gradle Buile
      - name: Build with Gradle
        run: |
          sudo chmod +x ./gradlew
          sudo ./gradlew clean build
      # DockerHub 로그인
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      # DockerHub Push
      - name: Build and Push Docker image
        run: |
          sudo docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/travelbag-app-dev .
          sudo docker push ${{ secrets.DOCKER_HUB_USERNAME }}/travelbag-app-dev

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # AWS 배포
      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /Backend
            sudo docker-compose stop
            sudo docker-compose rm -f
            sudo docker rmi ${{ secrets.DOCKER_HUB_USERNAME }}/travelbag-app-dev:latest
            sudo docker-compose up -d